package com.qaiser.hyra.namazapplication;

import java.util.ArrayList;

public class ArabicWordsArraylists {

    ArrayList arrayList1;

    ArrayList TakbeerArray;
    ArrayList RukuArray;
    ArrayList SalamArray;

    public ArrayList getArrayList1() {
        arrayList1 = new ArrayList();
        arrayList1.add("الله اكبر");
        arrayList1.add("الله واكبر الله واكبر");
        arrayList1.add("الله و اكبر");
        arrayList1.add("الله واكبر الله واكبر");
        arrayList1.add("الله واكبر الله واكبر");
        arrayList1.add("الله و اكبر الله و اكبر");
        arrayList1.add("الله واكبر");
        arrayList1.add("و الله اكبر");
        arrayList1.add("العفو اكبر");
        arrayList1.add("الله و اكبر و");
        arrayList1.add("الله و اكبر و");

        arrayList1.add("سميه الاولى من امده");
        arrayList1.add("سميع الله لمن حمده");
        arrayList1.add("سميه الاولى من امير");
        arrayList1.add("سمع الله لمن حمده");
        arrayList1.add("سمع الله لمن حميده ");
        arrayList1.add("سميره الاولى من امده");
        arrayList1.add("سمير الاولى من امده");
        arrayList1.add("سميه الاولى من اميركا");
        arrayList1.add("اغنيه الاولى من حميده");
        arrayList1.add("اغنيه الله اليمن حميده");
        arrayList1.add("اغنيه الاهلي مين حميده");
        arrayList1.add("اغنيه لا اليمن حميده");
        arrayList1.add("اغنيه الا اليمن حميده");
        arrayList1.add("سميه الاولى منها مده");
        arrayList1.add("سامي الاولى منها مده");
        arrayList1.add("سمير الاولى منها مده");
        arrayList1.add("سامي الاولى منها ميدان");
        arrayList1.add("سميه الاولى منها ميدان");
        arrayList1.add("امير لا اخليه وانها ميدان");
        arrayList1.add("مسامير لا اخليه وانها ميدان");
        arrayList1.add("امير لا تخليني وانها ميدان");
        arrayList1.add("امير الاصليه و انها ميدان");
        arrayList1.add("امير لا تقلي وانها ميدان");
        arrayList1.add("اغنيه الاولى من هذا");
        arrayList1.add("سميره الله اليمن حميده");
        arrayList1.add("اغنيه الاولى منها بيضاء");
        arrayList1.add("اغنيه الاوليه من هذا");
        arrayList1.add("اغنيه الاولى من هنا");
        arrayList1.add("اغنيه الاولي من هذا");
        arrayList1.add("سمير لو في اليمن حميده");
        arrayList1.add("سمير القلاف اليمني حميده");
        arrayList1.add("سمير الاولى من حميده");
        arrayList1.add("سمير لو في اليمن الحديده");
        arrayList1.add("سمير لا في اليمن حميده");
        arrayList1.add("سمير لو في اليمن حميده");
        arrayList1.add("سمير الله لمن حمده");
        arrayList1.add("سميه الله لمن حمده");
        arrayList1.add("سمير لو في اليمن الحديده");
        arrayList1.add("سمير الله لمن حميده");
        arrayList1.add("سمير لو في اليمن حميده");
        arrayList1.add("سمير الله في اليمن حميده");
        arrayList1.add("سمير لا في اليمن حميده");
        arrayList1.add("سمير الله لمن حميده");
        arrayList1.add("سميه الله في اليمن حميده");
        arrayList1.add("سمير الله لمن حمده");
        arrayList1.add("سمير الله اليمن حميده");
        arrayList1.add("سميه الله اليمن حميده");
        arrayList1.add("سميه الله لمن حمده");
        arrayList1.add("سميره الله لمن حمده");
        arrayList1.add("سميره الله لمن حمده");
        arrayList1.add("سامي الاولى منهم يده");
        arrayList1.add("سميه الاولى من الميدان");
        arrayList1.add("سميه الاول ياماها مينا");
        arrayList1.add("سميه الاولى من حميده");
        arrayList1.add(" مسامير الاولى من امير");
        arrayList1.add("سميه الاولى من اميلي");
        arrayList1.add(" اغنيه الاولى من ميدان");
        arrayList1.add(" سمير لونها ميدان");
        arrayList1.add(" سمير لون منها ميدان");
        arrayList1.add("حسام يالله لمن حميده");
        arrayList1.add("جميع الاهل من حميده");
        arrayList1.add("جميع الاهل منهم يده");
        arrayList1.add("سامي الاول منهم يده");
        arrayList1.add("سميه لو اليمن حميده");
        arrayList1.add("ساميه لوفلي منهم يده");
        arrayList1.add("جميع الاهل منها ميدو");
        arrayList1.add("ساميه لوفلي منهم يده");
        arrayList1.add("سمير لمن حميده");
        arrayList1.add("سميه الاولى منها ميدو");
        arrayList1.add("سميره لمن حميده");
        arrayList1.add("سمير لو اليمن حميده");
        arrayList1.add("سامي الله اليمن حميده");
        arrayList1.add("جميل و لمن حميدان");
        arrayList1.add("سمير نوفل من حميده");
        arrayList1.add("اميره لمن حمده");
        arrayList1.add("سميه لوفلي من حميده");
        arrayList1.add("سميرنوف ليمون حميده");
        arrayList1.add(" جميل و لمن حمده");
        arrayList1.add("جميله المنام يده");
        arrayList1.add("جميع الاول منهم");
        arrayList1.add("سميره لمن حميدو");
        arrayList1.add("اليمن حميدو");
        arrayList1.add("جميله اليمن حميده");
        arrayList1.add("جميله لمن حمده");
        arrayList1.add("جميله اليمن همدان");
        arrayList1.add("جميل و هو لمن حمده");
        arrayList1.add("سمير لو لمن حميده");
        arrayList1.add("حسام ياللوم اليمن حميده");
        arrayList1.add("سميرنوف لمن حمده");
        arrayList1.add("سلام ياللي من حميده");
        arrayList1.add("سميره لمن حمده");
        arrayList1.add("سلوم لمن حمده");
        arrayList1.add("سميع الله اليمن حميده");
        arrayList1.add("ساميه لوفلي من حميده");
        arrayList1.add("سميه الاهل من حميده");
        arrayList1.add("الاهلي من حميده");
        arrayList1.add("سامي ياللي من حميدو");
        arrayList1.add("سمير اللول من حميده");
        arrayList1.add("سمير اللول من حميده");
        arrayList1.add("سامي ياللي من حميده");
        arrayList1.add("جميع الله اليمن حميده");
        arrayList1.add("سامي ياللي من حميده");
        arrayList1.add("جميله اليمن حميدو");
        arrayList1.add("حسينيه لاهل من حميده");
        arrayList1.add("سامي الاول من حميده");
        arrayList1.add("يالله اليمن حميده");
        arrayList1.add("جميل و هناء حميده");
        arrayList1.add("سامي الاهلي من حميده");
        arrayList1.add("سميرنوف لمن حميده");
        arrayList1.add("سميره لمنع ميدان");
        arrayList1.add("سميه الاهلي بني حميده");
        arrayList1.add("سميه اليمن حميده");
        arrayList1.add("تسميه الاهلي من حميده");
        arrayList1.add("سمير جاهل من حميده");
        arrayList1.add("ساميه و الله اليمن حميده");
        arrayList1.add("سمير لو من حميده");
        arrayList1.add("اغنيه الاولى من املاء");
        arrayList1.add("يا الله لمن حمده");
        arrayList1.add("سمير لوحدي من حميده");
        arrayList1.add("جميله لمن حميده");
        arrayList1.add("سمير اللول من حميده");
        arrayList1.add("سمير لو هل من حميده");
        arrayList1.add("جميل و هنا حميدي");
        arrayList1.add("سميه الهيمان حميده");
        arrayList1.add("سميه لوفلي منهم");
        arrayList1.add("ساميه الله لمن حمده");
        arrayList1.add("ساميه الله اليمن حميده");
        arrayList1.add("اللهم انهم يدا");
        arrayList1.add("ساميه لولي منهم");
        arrayList1.add("سامي الاهلي منهم يدا");
        arrayList1.add("ساميه لمن حميده");
        arrayList1.add("الاهلي منهم يدا");
        arrayList1.add("سامي ياللي من هاميدا");
        arrayList1.add("سامي الاهلي منهم يلا");
        arrayList1.add("سامي يالله");
        arrayList1.add("اغنيه الاهلي منهم");
        arrayList1.add("ساميه و اليمن");
        arrayList1.add("قولي منهم يده");
        arrayList1.add("سميره اليمن هوندا");
        arrayList1.add("سميه لوفلي منها ميدان");
        arrayList1.add("اميره لمن حميدو");
        arrayList1.add("جميع اليمن حميده");
        arrayList1.add("تحميل الاولى من الحمل");
        arrayList1.add("ساميه للاهلي مهنا");
        arrayList1.add("سمير وليم حميده");
        arrayList1.add("سمير لمن حمده");
        arrayList1.add("اغنيه انا لك الحمد");
        arrayList1.add("سميلا في اليمن حمله");
        arrayList1.add("سميرنوف ليمون حميدو");
        arrayList1.add("سمير لوفلي من حميده");
        arrayList1.add("سمير لو اليمن حميدو");
        arrayList1.add("تحميل اغنيه محمد");
        arrayList1.add("تحميل افلام");
        arrayList1.add("تحميل افلام");

        arrayList1.add("السلام عليكم ورحمه الله");
        arrayList1.add("السلام عليكم و رحمه الله");
        arrayList1.add("السلام و عليكم و رحمه الله");
        arrayList1.add("افلام وليكون مثل");
        arrayList1.add("السلام عليكم و رحمه الله");
        arrayList1.add("السلام عليكم و رحمه الله");

        return arrayList1;
    }
    public ArrayList getTakbeerArray(){
        TakbeerArray=new ArrayList();
        TakbeerArray.add("الله اكبر");
        TakbeerArray.add("النوف و اكبر");
        TakbeerArray.add("الله واكبر الله واكبر");
        TakbeerArray.add("الاخوه اكبر");
        TakbeerArray.add("الاخوه قبل");
        TakbeerArray.add("اللوح و اكبر");
        TakbeerArray.add("الله و اكبر");
        TakbeerArray.add("الله واكبر الله واكبر");
        TakbeerArray.add("الله واكبر الله واكبر");
        TakbeerArray.add("الله و اكبر الله و اكبر");
        TakbeerArray.add("الله واكبر");
        TakbeerArray.add("و الله اكبر");
        TakbeerArray.add("العفو اكبر");
        TakbeerArray.add("الله و اكبر و");
        TakbeerArray.add("الله و اكبر و");
        TakbeerArray.add("ما هو اكبر");
        TakbeerArray.add("الاخوه قبل");
        TakbeerArray.add("هو اكبر");
        TakbeerArray.add("اللوف و اكبر");

        return TakbeerArray;
    }
    public ArrayList getRukuArrayy(){
        RukuArray=new ArrayList();
        RukuArray.add("سميه الاولى من امده");
        RukuArray.add("سميع الله لمن حمده");
        RukuArray.add("سميه الاولى من امير");
        RukuArray.add("سمع الله لمن حمده");
        RukuArray.add("قولي منهم يده");

        RukuArray.add("سميرنوف ليمون حميدو");
        RukuArray.add("سمير لوفلي من حميده");
        RukuArray.add("سمير لو اليمن حميدو");

        RukuArray.add("سمع الله لمن حميده ");
        RukuArray.add("سميره الاولى من امده");
        RukuArray.add("سمير الاولى من امده");
        RukuArray.add("سميه الاولى من اميركا");
        RukuArray.add("اغنيه الاولى من حميده");
        RukuArray.add("اغنيه الله اليمن حميده");
        RukuArray.add("اغنيه الاهلي مين حميده");
        RukuArray.add("اغنيه لا اليمن حميده");
        RukuArray.add("اغنيه الا اليمن حميده");
        RukuArray.add("سميه الاولى منها مده");
        RukuArray.add("سامي الاولى منها مده");
        RukuArray.add("سمير الاولى منها مده");
        RukuArray.add("سامي الاولى منها ميدان");
        RukuArray.add("سميه الاولى منها ميدان");
        RukuArray.add("امير لا اخليه وانها ميدان");
        RukuArray.add("مسامير لا اخليه وانها ميدان");
        RukuArray.add("امير لا تخليني وانها ميدان");
        RukuArray.add("امير الاصليه و انها ميدان");
        RukuArray.add("امير لا تقلي وانها ميدان");
        RukuArray.add("اغنيه الاولى من هذا");
        RukuArray.add("سميره الله اليمن حميده");
        RukuArray.add("اغنيه الاولى منها بيضاء");
        RukuArray.add("اغنيه الاوليه من هذا");
        RukuArray.add("اغنيه الاولى من هنا");
        RukuArray.add("اغنيه الاولي من هذا");
        RukuArray.add("سمير لو في اليمن حميده");
        RukuArray.add("سمير القلاف اليمني حميده");
        RukuArray.add("سمير الاولى من حميده");
        RukuArray.add("سمير لو في اليمن الحديده");
        RukuArray.add("سمير لا في اليمن حميده");
        RukuArray.add("سمير لو في اليمن حميده");
        RukuArray.add("سمير الله لمن حمده");
        RukuArray.add("سميه الله لمن حمده");
        RukuArray.add("سمير لو في اليمن الحديده");
        RukuArray.add("سمير الله لمن حميده");
        RukuArray.add("سمير لو في اليمن حميده");
        RukuArray.add("سمير الله في اليمن حميده");
        RukuArray.add("سمير لا في اليمن حميده");
        RukuArray.add("سمير الله لمن حميده");
        RukuArray.add("سميه الله في اليمن حميده");
        RukuArray.add("سمير الله لمن حمده");
        RukuArray.add("سمير الله اليمن حميده");
        RukuArray.add("سميه الله اليمن حميده");
        RukuArray.add("سميه الله لمن حمده");
        RukuArray.add("سميره الله لمن حمده");
        RukuArray.add("سميره الله لمن حمده");
        RukuArray.add("سامي الاولى منهم يده");
        RukuArray.add("سميه الاولى من الميدان");
        RukuArray.add("سميه الاول ياماها مينا");
        RukuArray.add("سميه الاولى من حميده");
        RukuArray.add(" مسامير الاولى من امير");
        RukuArray.add("سميه الاولى من اميلي");
        RukuArray.add(" اغنيه الاولى من ميدان");
        RukuArray.add(" سمير لونها ميدان");
        RukuArray.add(" سمير لون منها ميدان");
        RukuArray.add("حسام يالله لمن حميده");
        RukuArray.add("جميع الاهل من حميده");
        RukuArray.add("جميع الاهل منهم يده");
        RukuArray.add("سامي الاول منهم يده");
        RukuArray.add("سميه لو اليمن حميده");
        RukuArray.add("ساميه لوفلي منهم يده");
        RukuArray.add("جميع الاهل منها ميدو");
        RukuArray.add("ساميه لوفلي منهم يده");
        RukuArray.add("سمير لمن حميده");
        RukuArray.add("سميه الاولى منها ميدو");
        RukuArray.add("سميره لمن حميده");
        RukuArray.add("سمير لو اليمن حميده");
        RukuArray.add("سامي الله اليمن حميده");
        RukuArray.add("جميل و لمن حميدان");
        RukuArray.add("سمير نوفل من حميده");
        RukuArray.add("اميره لمن حمده");
        RukuArray.add("سميه لوفلي من حميده");
        RukuArray.add("سميرنوف ليمون حميده");
        RukuArray.add(" جميل و لمن حمده");
        RukuArray.add("جميله المنام يده");
        RukuArray.add("جميع الاول منهم");
        RukuArray.add("سميره لمن حميدو");
        RukuArray.add("اليمن حميدو");
        RukuArray.add("جميله اليمن حميده");
        RukuArray.add("جميله لمن حمده");
        RukuArray.add("جميله اليمن همدان");
        RukuArray.add("جميل و هو لمن حمده");
        RukuArray.add("سمير لو لمن حميده");
        RukuArray.add("حسام ياللوم اليمن حميده");
        RukuArray.add("سميرنوف لمن حمده");
        RukuArray.add("سلام ياللي من حميده");
        RukuArray.add("سميره لمن حمده");
        RukuArray.add("سلوم لمن حمده");
        RukuArray.add("سميع الله اليمن حميده");
        RukuArray.add("ساميه لوفلي من حميده");
        RukuArray.add("سميه الاهل من حميده");
        RukuArray.add("الاهلي من حميده");
        RukuArray.add("سامي ياللي من حميدو");
        RukuArray.add("سمير اللول من حميده");
        RukuArray.add("سمير اللول من حميده");
        RukuArray.add("سامي ياللي من حميده");
        RukuArray.add("جميع الله اليمن حميده");
        RukuArray.add("سامي ياللي من حميده");
        RukuArray.add("جميله اليمن حميدو");
        RukuArray.add("حسينيه لاهل من حميده");
        RukuArray.add("سامي الاول من حميده");
        RukuArray.add("يالله اليمن حميده");
        RukuArray.add("جميل و هناء حميده");
        RukuArray.add("سامي الاهلي من حميده");
        RukuArray.add("سميرنوف لمن حميده");
        RukuArray.add("سميره لمنع ميدان");
        RukuArray.add("سميه الاهلي بني حميده");
        RukuArray.add("سميه اليمن حميده");
        RukuArray.add("تسميه الاهلي من حميده");
        RukuArray.add("سمير جاهل من حميده");
        RukuArray.add("ساميه و الله اليمن حميده");
        RukuArray.add("سمير لو من حميده");
        RukuArray.add("اغنيه الاولى من املاء");
        RukuArray.add("يا الله لمن حمده");
        RukuArray.add("سمير لوحدي من حميده");
        RukuArray.add("جميله لمن حميده");
        RukuArray.add("سمير اللول من حميده");
        RukuArray.add("سمير لو هل من حميده");
        RukuArray.add("جميل و هنا حميدي");
        RukuArray.add("سميه الهيمان حميده");
        RukuArray.add("سميه لوفلي منهم");
        RukuArray.add("ساميه الله لمن حمده");
        RukuArray.add("ساميه الله اليمن حميده");
        RukuArray.add("اللهم انهم يدا");
        RukuArray.add("ساميه لولي منهم");
        RukuArray.add("سامي الاهلي منهم يدا");
        RukuArray.add("ساميه لمن حميده");
        RukuArray.add("الاهلي منهم يدا");
        RukuArray.add("سامي ياللي من هاميدا");
        RukuArray.add("سامي الاهلي منهم يلا");
        RukuArray.add("سامي يالله");
        RukuArray.add("اغنيه الاهلي منهم");
        RukuArray.add("ساميه و اليمن");
        RukuArray.add("قولي منهم يده");
        RukuArray.add("سميره اليمن هوندا");
        RukuArray.add("سميه لوفلي منها ميدان");
        RukuArray.add("اميره لمن حميدو");
        RukuArray.add("سميرنوف ليمون حميدو");
        RukuArray.add("جميع اليمن حميده");
        RukuArray.add("تحميل الاولى من الحمل");
        RukuArray.add("ساميه للاهلي مهنا");
        RukuArray.add("سمير وليم حميده");
        RukuArray.add("سمير لمن حمده");
        RukuArray.add("اغنيه انا لك الحمد");
        RukuArray.add("سميلا في اليمن حمله");
        RukuArray.add("تحميل اغنيه محمد");
        RukuArray.add("تحميل افلام");
        RukuArray.add("تحميل افلام");
        RukuArray.add("سميه الاهلي منهم يده");
        RukuArray.add("سمير البابلي منهم يده");
        RukuArray.add("سمير لو هل من هوندا");
        RukuArray.add("جميع الاهل منهم يده");
        RukuArray.add("سميه لوفلي من حميده");
        return RukuArray;
    }

    public ArrayList getSalamArray(){
       SalamArray=new ArrayList();
        SalamArray.add("السلام عليكم ورحمه الله");
        SalamArray.add("السلام عليكم و رحمه الله");
        SalamArray.add("السلام و عليكم و رحمه الله");
        SalamArray.add("افلام وليكون مثل");
        SalamArray.add("السلام عليكم و رحمه الله");
        SalamArray.add("السلام عليكم و رحمه الله");

        return SalamArray;
    }




}
